name: Sample Pipeline_1676327198129
stages:
  - name: build
    spec:
      platform:
        arch: amd64
        os: linux
      steps:
        - name: echo
          spec:
            run: echo hello world
          type: script
    type: ci
version: 1
