name: Sample Pipeline_1676415121326
stages:
  - name: build1
    spec:
      steps:
        - name: go_build
          spec:
            run: go build
          type: script
        - name: go_test
          spec:
            run: wow1
          type: script
    type: ci
  - name: build2
    spec:
      steps:
        - name: go_build
          spec:
            run: go build
          type: script
        - name: go_test
          spec:
            run: go hawks
          type: script
    type: ci
version: 1
